export const GET_FOOD_ITEMS = "GET_FOOD_ITEMS";
export const GET_FOOD_ITEMS_SUCCESS = "GET_FOOD_ITEMS_SUCCESS";
export const GET_FOOD_ITEMS_FAIL = "ET_FOOD_ITEMS_FAIL";

export const GET_FOOD_DETAILS = "GET_FOOD_DETAILS";
export const GET_FOOD_DETAILS_SUCCESS = "GET_FOOD_DETAILS_SUCCESS";
export const GET_FOOD_DETAILS_FAIL = "GET_FOOD_DETAILS_FAIL";